Repository Cockatoo-AI-Org/Cockatoo.AI, pull requests merged in 2024-01, with the labels that each got.

#18 #6 - Update `README.md` to include survey of Whisper in section `For Model A (Speech to text, STT)`
  README.md
Labels: research

#21 initiate folder structure
  .github/workflows/ci-build.yml
  demo/README.md
  docs/README.md
  docs/conf.py
  experiments/experiment1.ipynb
  src/__init__.py
  tests/__init__.py
Labels: documentation

#26 add poetry, conda, Makefile
  .gitignore
  Makefile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement, good first issue
